---
- hosts: odo
  gather_facts: false
  become: yes
  vars_files:
    - vars/main.yml
    - vars/x-token.yml
    - vars/site-dtc.yml

  tasks:
    - name: Get token task
      import_tasks: tasks/x-token.yml
    - name: Get List Sites
      import_tasks: tasks/get-sites-dtc.yml
    - name: Get Config DTC
      import_tasks: tasks/get-config-dtc.yml
    - name: Deploy Connector
      import_tasks: tasks/deploy-connector.yml


