---
- hosts: localhost
  connection: local 
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/token.yml

  tasks:
    - name: Get token task
      import_tasks: tasks/token.yml

    - name: Get List Sites
      import_tasks: tasks/get-sites.yml


