---
- hosts: all
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/x-token.yml
    - vars/key.yml

  tasks:
    - name: Get token task
      import_tasks: tasks/x-token.yml

    - name: Get Services
      import_tasks: tasks/get-services.yml

