---

- name: Create IDP Azure
  uri:
    url: "https://cloudinfra-gw.portal.checkpoint.com/api/v2/idpConfig"
    method: POST
    headers:
      Content-Type: "application/json"
      x-access-token: "{{x_token}}"
      cookie: "{{cookie}}"
    body_format: json
    body: "{{ idp_azure | to_json }}"
  register: idpsaml
  failed_when: idpsaml.status != 200 and idpsaml.status != 201 and idpsaml.status != 204

- name: Print idpsaml
  debug:
    var: idpsaml.json

