---
- name: Fetch Applicant
  uri:
    url: "https://graph.microsoft.com/v1.0/applications/af11ea3f-3a0a-43a7-b7cc-0d73e7a882a4"
    method: PATCH
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ ad_token }}"
    body_format: json
    body: "{{ set_saml_url | to_json }}"
  register: saml
  failed_when: saml.status != 200 and saml.status != 201 and saml.status != 204

- name: Print saml
  debug:
    var: saml

