---
- hosts: localhost
  connection: local 
  gather_facts: false
  vars_files:
    - ../vars/main.yml
    - ../vars/x-token.yml
    - ../vars/user-device.yml

  tasks:
    - name: Get token task
      import_tasks: ../tasks/x-token.yml

    - name: Create User
      import_tasks: ../tasks/users-devices/create-user.yml


